### ISSUE TITLE
HQM File Corrupted

### ISSUE THREAD

**Issue by Sir-Will** [CannibalVox/NoTimeFix#2]
hey,

our HQM SaveFile got corrupted with the Agrarian Skies 2 modpack. Can you look if you can find out what happened with it and maybe add a fix for it to your mod?
Here the file: https://mega.co.nz/#!rg5BTYTY!Z6n-BKUUXLnntHgKzMubclD9OZ7wd80Q0Wx83ka02VU

The error which shows up in the client log if I try to open the questbook:

```
java.lang.ArrayIndexOutOfBoundsException: 32764
    at hardcorequesting.network.PacketHandler.getDataReaderForPacket(PacketHandler.java:215)
    at hardcorequesting.network.PacketHandler.onPacketData(PacketHandler.java:117)
    at hardcorequesting.network.PacketHandler.onClientPacket(PacketHandler.java:105)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_722_PacketHandler_onClientPacket_ClientCustomPacketEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103)
    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30)
    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
java.lang.ArrayIndexOutOfBoundsException: 157
    at hardcorequesting.network.PacketHandler.getDataReaderForPacket(PacketHandler.java:215)
    at hardcorequesting.network.PacketHandler.onPacketData(PacketHandler.java:117)
    at hardcorequesting.network.PacketHandler.onClientPacket(PacketHandler.java:105)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_722_PacketHandler_onClientPacket_ClientCustomPacketEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103)
    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30)
    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Sir-Will** [comment]
@CannibalVox any news? :/

**Comment by CannibalVox** [comment]
Hi, SirWilli, we get this error every time we start a server with Blightfall, but it doesn't actually seem to matter and servers start just fine.

**Comment by CannibalVox** [comment]
Oh, hey, Ag Skies 2?  Doesn't that use a new secret version of HQM?  That probably won't work with notimefix.

**Comment by Sir-Will** [comment]
The error doesn't show up in the server console. It shows up in the client console if I try to open the book. If it is not broken the error is not there.

Hm no, it's the normal version. HQM-The Journey (4.2.4)

**Comment by CannibalVox** [comment]
Can you try downgrading to 4.2.3?

**Comment by CannibalVox** [comment]
Also, this mod needs to be on the server side not the client side.  Being on the client side doesn't hurt, but it also doesn't fix anything.

**Comment by Sir-Will** [comment]
I don't think I can as the client needs to have the same version.

I'm aware of that and at the moment it is only on the server.
